[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "frontend"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  FLASK_ENV = "production"
  
[context.deploy-preview.environment]
  FLASK_ENV = "development"
